##===- lib/DSA/Makefile ------------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../..
BUILD_RELINKED=1
SHARED_LIBRARY=1
LIBRARYNAME = LLVMDataStructure

include $(LEVEL)/Makefile.common

CFlags += -Wno-deprecated
