#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=FreeListAllocator FL2Allocator PreRT DynamicTypeChecks DynCount

include $(LEVEL)/Makefile.common
