#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=PoolAllocator FreeListAllocator FL2Allocator

include $(LEVEL)/Makefile.common
