LEVEL = ../..
BYTECODE_LIBRARY=1
SHARED_LIBRARY=1
LIBRARYNAME=poolalloc_rt

CXXFLAGS += -fno-exceptions

include $(LEVEL)/Makefile.common

# Always build optimized and debug versions
all:: $(LIBNAME_OBJO) $(LIBNAME_OBJG)
