##===- lib/DSA/Makefile ------------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../..
LOADABLE_MODULE=1
BUILD_ARCHIVE = 1
LIBRARYNAME = librDSA

include $(LEVEL)/Makefile.common

CFlags += -Wno-deprecated
